/* ACE2X Knowledge OS v0.6.0 - generated by esbuild. Source: src/main.ts */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  RECORD_TYPES: () => RECORD_TYPES,
  default: () => ACE2XKnowledgeOSPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/meetingMode/view.ts
var import_obsidian = require("obsidian");

// src/meetingMode/capture.ts
function parseCaptureInput(raw, typeKeys) {
  const trimmed = raw.trim();
  if (!trimmed) return { type: null, body: "" };
  const pattern = new RegExp(`^(${typeKeys.join("|")})::\\s*(.+)$`, "i");
  const match = trimmed.match(pattern);
  if (!match) return { type: null, body: trimmed };
  return { type: match[1].toLowerCase(), body: match[2].trim() };
}
function buildCaptureLine(parsed, owner, bodyHasPersonLink) {
  if (!parsed.type) return `- ${parsed.body}`;
  const body = !bodyHasPersonLink && owner ? `${parsed.body} ${owner.canonicalLink}` : parsed.body;
  return `- ${parsed.type}:: ${body} s::o`;
}
async function appendLineToFile(app, file, line) {
  const content = await app.vault.read(file);
  const separator = content.length && !content.endsWith("\n") ? "\n" : "";
  await app.vault.modify(file, `${content}${separator}${line}
`);
}

// src/meetingMode/highlightExtension.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var setHighlightLines = import_state.StateEffect.define();
var highlightLineDeco = import_view.Decoration.line({ attributes: { class: "aceto-mm-line-highlight" } });
var highlightLinesField = import_state.StateField.define({
  create() {
    return import_view.Decoration.none;
  },
  update(deco, tr) {
    deco = deco.map(tr.changes);
    for (const effect of tr.effects) {
      if (!effect.is(setHighlightLines)) continue;
      const lineNumbers = effect.value;
      if (!lineNumbers.length) {
        deco = import_view.Decoration.none;
        continue;
      }
      const ranges = [];
      for (const lineNumber of lineNumbers) {
        if (lineNumber < 1 || lineNumber > tr.state.doc.lines) continue;
        const line = tr.state.doc.line(lineNumber);
        ranges.push(highlightLineDeco.range(line.from));
      }
      deco = import_view.Decoration.set(ranges, true);
    }
    return deco;
  },
  provide: (field) => import_view.EditorView.decorations.from(field)
});

// src/meetingMode/view.ts
var VIEW_TYPE_MEETING_MODE = "ace2x-meeting-mode";
function parseWikilinkString(raw) {
  const match = String(raw || "").trim().match(/^\[\[([^\]]+)\]\]$/);
  if (!match) return null;
  const [targetPart, alias] = match[1].split("|");
  const target = targetPart.split("#")[0].trim();
  if (!target) return null;
  return { target, alias: (alias == null ? void 0 : alias.trim()) || null };
}
var MeetingModeView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeSourceFile = null;
    this.currentOwner = null;
    this.personSearchOwner = null;
    this.highlightClearTimer = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MEETING_MODE;
  }
  getDisplayText() {
    return "Meeting Mode";
  }
  getIcon() {
    return "target";
  }
  async onOpen() {
    var _a;
    const container = this.contentEl;
    container.empty();
    container.addClass("aceto-meeting-mode");
    const header = container.createDiv({ cls: "aceto-mm-header" });
    this.headerTitleEl = header.createEl("div", { cls: "aceto-mm-title", text: "No active meeting note" });
    this.headerDateEl = header.createEl("div", { cls: "aceto-mm-date" });
    this.ownerSectionEl = container.createDiv({ cls: "aceto-mm-owner" });
    this.ownerSectionEl.createEl("div", { cls: "aceto-mm-section-label", text: "Owner" });
    this.ownerSectionEl.createEl("div", { cls: "aceto-mm-owner-value", text: "\u2014" });
    const captureSection = container.createDiv({ cls: "aceto-mm-capture" });
    captureSection.createEl("div", { cls: "aceto-mm-section-label", text: "Quick Capture" });
    this.captureInputEl = captureSection.createEl("input", {
      cls: "aceto-mm-capture-input",
      attr: { type: "text", placeholder: "d:: r:: i:: e:: a:: or plain text, then Enter" }
    });
    this.captureInputEl.addEventListener("keydown", (evt) => {
      if (evt.key !== "Enter") return;
      evt.preventDefault();
      void this.handleCaptureSubmit();
    });
    this.countersEl = container.createDiv({ cls: "aceto-mm-counters" });
    const openItemsSection = container.createDiv({ cls: "aceto-mm-open-items" });
    openItemsSection.createEl("div", { cls: "aceto-mm-section-label", text: "Open Items" });
    this.personSearchEl = openItemsSection.createEl("input", {
      cls: "aceto-mm-open-items-search",
      attr: { type: "text", placeholder: "Search by person (all open items, vault-wide)...", list: "aceto-mm-person-datalist" }
    });
    const datalist = openItemsSection.createEl("datalist", { attr: { id: "aceto-mm-person-datalist" } });
    for (const path of this.plugin.personFilePaths()) {
      datalist.createEl("option", { attr: { value: ((_a = path.split("/").pop()) == null ? void 0 : _a.replace(/\.md$/i, "")) || path } });
    }
    this.personSearchEl.addEventListener("input", () => {
      const value = this.personSearchEl.value.trim();
      this.personSearchOwner = value ? this.resolvePersonByName(value) : null;
      this.renderOpenItems();
    });
    const scopeRow = openItemsSection.createDiv({ cls: "aceto-mm-open-items-scope" });
    this.openItemsScopeEl = scopeRow.createEl("span");
    const clearButton = scopeRow.createEl("button", { cls: "aceto-mm-clear-person-search", text: "Clear" });
    clearButton.addEventListener("click", () => {
      this.personSearchEl.value = "";
      this.personSearchOwner = null;
      this.renderOpenItems();
    });
    this.openItemsSearchEl = openItemsSection.createEl("input", {
      cls: "aceto-mm-open-items-search",
      attr: { type: "text", placeholder: "Filter by text..." }
    });
    this.openItemsSearchEl.addEventListener("input", () => this.renderOpenItems());
    this.openItemsEl = openItemsSection.createDiv({ cls: "aceto-mm-open-items-list" });
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.refreshHeader()));
    this.registerEvent(this.app.workspace.on("file-open", () => this.refreshHeader()));
    this.registerEvent(this.app.metadataCache.on("changed", (file) => {
      if (this.activeSourceFile && file.path === this.activeSourceFile.path) this.refreshHeader();
    }));
    this.refreshHeader();
  }
  async onClose() {
    this.contentEl.empty();
  }
  setPrefill(prefix) {
    if (!this.captureInputEl) return;
    this.captureInputEl.value = prefix ? `${prefix}:: ` : "";
    this.captureInputEl.focus();
    if (prefix) this.captureInputEl.setSelectionRange(this.captureInputEl.value.length, this.captureInputEl.value.length);
  }
  resolveActiveSourceFile() {
    const active = this.app.workspace.getActiveFile();
    return active instanceof import_obsidian.TFile && active.extension === "md" ? active : null;
  }
  refreshHeader() {
    const file = this.resolveActiveSourceFile();
    this.activeSourceFile = file;
    if (!file) {
      this.headerTitleEl.setText("No active meeting note");
      this.headerDateEl.setText("");
    } else {
      this.headerTitleEl.setText(file.basename);
      this.headerDateEl.setText(this.plugin.getSourceDate(file));
    }
    this.refreshOwner();
    this.refreshCounters();
  }
  refreshCounters() {
    var _a;
    this.countersEl.empty();
    if (!this.plugin.settings.meetingModeShowCounters) return;
    const file = this.activeSourceFile;
    const records = file && ((_a = this.plugin.index[file.path]) == null ? void 0 : _a.records) || [];
    const labels = this.plugin.recordTypeLabels();
    const counts = {};
    for (const record of records) counts[record.type] = (counts[record.type] || 0) + 1;
    for (const type of this.plugin.recordTypeKeys()) {
      const count = counts[type] || 0;
      const counterEl = this.countersEl.createEl("span", { cls: "aceto-mm-counter", text: `${labels[type] || type}: ${count}` });
      if (count > 0) {
        counterEl.addClass("is-clickable");
        counterEl.addEventListener("click", () => this.highlightRecordsOfType(type));
      }
    }
  }
  findActiveMarkdownLeaf(file) {
    return this.app.workspace.getLeavesOfType("markdown").find((leaf) => {
      var _a, _b;
      return ((_b = (_a = leaf.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === file.path;
    }) || null;
  }
  highlightRecordsOfType(typeKey) {
    var _a;
    const file = this.activeSourceFile;
    if (!file) return;
    const leaf = this.findActiveMarkdownLeaf(file);
    const markdownView = (leaf == null ? void 0 : leaf.view) instanceof import_obsidian.MarkdownView ? leaf.view : null;
    const cm = (_a = markdownView == null ? void 0 : markdownView.editor) == null ? void 0 : _a.cm;
    if (!leaf || !markdownView || !cm) return;
    this.app.workspace.revealLeaf(leaf);
    const content = markdownView.editor.getValue();
    const lineNumbers = this.plugin.findAllSourceLineNumbers(content, typeKey).map((i) => i + 1);
    cm.dispatch({ effects: setHighlightLines.of(lineNumbers) });
    if (this.highlightClearTimer !== null) window.clearTimeout(this.highlightClearTimer);
    this.highlightClearTimer = window.setTimeout(() => {
      cm.dispatch({ effects: setHighlightLines.of([]) });
      this.highlightClearTimer = null;
    }, 4e3);
  }
  async handleCaptureSubmit() {
    const raw = this.captureInputEl.value;
    if (!raw.trim()) return;
    const file = this.activeSourceFile;
    if (!file) return;
    const parsed = parseCaptureInput(raw, this.plugin.recordTypeKeys());
    const bodyHasPersonLink = Boolean(
      parsed.type && this.plugin.parseWikiLinks(parsed.body).some((link) => this.plugin.resolvePersonLink(link, file))
    );
    const owner = this.currentOwner ? { basename: this.currentOwner.basename, canonicalLink: this.currentOwner.canonicalLink } : null;
    const line = buildCaptureLine(parsed, owner, bodyHasPersonLink);
    await appendLineToFile(this.app, file, line);
    if (parsed.type) await this.plugin.syncFile(file, false);
    this.refreshCounters();
    this.renderOpenItems();
    let nextPrefix = null;
    if (this.plugin.settings.meetingModeRememberCategory && parsed.type) {
      nextPrefix = parsed.type;
      this.plugin.settings.lastCapturePrefix = parsed.type;
      void this.plugin.persist();
    }
    if (this.plugin.settings.meetingModeFocusAfterSave) {
      this.setPrefill(nextPrefix);
    } else {
      this.captureInputEl.value = nextPrefix ? `${nextPrefix}:: ` : "";
    }
  }
  frontmatterLinksToPeople(file, fieldValue) {
    const list = Array.isArray(fieldValue) ? fieldValue : fieldValue ? [fieldValue] : [];
    const resolved = [];
    for (const entry of list) {
      const link = parseWikilinkString(entry);
      if (!link) continue;
      const person = this.plugin.resolvePersonLink(link, file);
      if (person) resolved.push(person);
    }
    return resolved;
  }
  resolveParticipants(file) {
    var _a;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const resolved = [];
    const seen = /* @__PURE__ */ new Set();
    for (const field of ["participants", "people", "owner"]) {
      for (const person of this.frontmatterLinksToPeople(file, fm == null ? void 0 : fm[field])) {
        if (!seen.has(person.path)) {
          seen.add(person.path);
          resolved.push(person);
        }
      }
    }
    const yourPath = String(this.plugin.settings.yourPersonNote || "");
    return yourPath ? resolved.filter((p) => p.path !== yourPath) : resolved;
  }
  resolveExplicitOwner(file) {
    var _a;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    return this.frontmatterLinksToPeople(file, fm == null ? void 0 : fm.owner)[0] || null;
  }
  personEntryFromPath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile)) return null;
    return {
      path: file.path,
      basename: file.basename,
      display: file.basename,
      canonicalLink: `[[${file.path.replace(/\.md$/i, "")}|${file.basename}]]`
    };
  }
  resolvePersonByName(name) {
    const target = name.trim().toLowerCase();
    if (!target) return null;
    for (const path of this.plugin.personFilePaths()) {
      const basename = (path.split("/").pop() || path).replace(/\.md$/i, "");
      if (basename.toLowerCase() === target) return this.personEntryFromPath(path);
    }
    return null;
  }
  refreshOwner() {
    this.ownerSectionEl.empty();
    this.ownerSectionEl.createEl("div", { cls: "aceto-mm-section-label", text: "Owner" });
    const file = this.activeSourceFile;
    const candidates = file ? this.resolveParticipants(file) : [];
    if (!candidates.length) {
      this.currentOwner = null;
      this.ownerSectionEl.createEl("div", {
        cls: "aceto-mm-owner-value",
        text: "No owner detected \u2014 include [[Person]] in the capture line"
      });
      this.renderOpenItems();
      return;
    }
    const select = this.ownerSectionEl.createEl("select", { cls: "aceto-mm-owner-select" });
    for (const person of candidates) {
      select.createEl("option", { value: person.path, text: person.basename });
    }
    let defaultPath = candidates[0].path;
    const explicitOwner = file ? this.resolveExplicitOwner(file) : null;
    if (this.plugin.settings.meetingModeRememberOwner && this.plugin.settings.lastOwnerPath && candidates.some((c) => c.path === this.plugin.settings.lastOwnerPath)) {
      defaultPath = this.plugin.settings.lastOwnerPath;
    }
    if (explicitOwner && candidates.some((c) => c.path === explicitOwner.path)) {
      defaultPath = explicitOwner.path;
    }
    select.value = defaultPath;
    this.currentOwner = candidates.find((c) => c.path === defaultPath) || candidates[0];
    select.addEventListener("change", () => {
      this.currentOwner = candidates.find((c) => c.path === select.value) || null;
      if (this.plugin.settings.meetingModeRememberOwner && this.currentOwner) {
        this.plugin.settings.lastOwnerPath = this.currentOwner.path;
        void this.plugin.persist();
      }
      this.renderOpenItems();
    });
    this.renderOpenItems();
  }
  queryOpenItems() {
    var _a;
    const effectiveOwner = this.personSearchOwner || this.currentOwner;
    const folders = this.plugin.recordFolderPaths();
    const rows = [];
    for (const file of this.app.vault.getMarkdownFiles()) {
      if (!folders.some((folder) => file.path === folder || file.path.startsWith(folder + "/"))) continue;
      const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
      if (!fm || !fm.record_id || !fm.source_path) continue;
      if (String(fm.status || "").toLowerCase() === "done") continue;
      if (effectiveOwner) {
        const ownerPaths = this.frontmatterLinksToPeople(file, fm.owner).map((p) => p.path);
        if (!ownerPaths.includes(effectiveOwner.path)) continue;
      }
      rows.push({
        file,
        sentence: String(fm.sentence || file.basename),
        sourcePath: String(fm.source_path || ""),
        type: String(fm.type || "")
      });
    }
    rows.sort((a, b) => a.sentence.localeCompare(b.sentence));
    return rows;
  }
  renderOpenItems() {
    var _a, _b, _c;
    if (!this.openItemsEl) return;
    this.openItemsEl.empty();
    if (this.personSearchOwner) {
      this.openItemsScopeEl.setText(`Vault-wide open items for ${this.personSearchOwner.basename}`);
      (_a = this.openItemsScopeEl.parentElement) == null ? void 0 : _a.addClass("is-active");
    } else if (this.currentOwner) {
      this.openItemsScopeEl.setText(`Open items for ${this.currentOwner.basename}`);
      (_b = this.openItemsScopeEl.parentElement) == null ? void 0 : _b.removeClass("is-active");
    } else {
      this.openItemsScopeEl.setText("All open items (vault-wide)");
      (_c = this.openItemsScopeEl.parentElement) == null ? void 0 : _c.removeClass("is-active");
    }
    const query = this.openItemsSearchEl.value.trim().toLowerCase();
    const rows = this.queryOpenItems().filter((row) => !query || row.sentence.toLowerCase().includes(query));
    if (!rows.length) {
      this.openItemsEl.createEl("div", { cls: "aceto-mm-open-items-empty", text: "No open items." });
      return;
    }
    if (this.personSearchOwner) {
      this.renderOpenItemsGroupedByType(rows);
    } else {
      for (const row of rows) this.renderOpenItemRow(this.openItemsEl, row);
    }
  }
  renderOpenItemsGroupedByType(rows) {
    const labels = this.plugin.recordTypeLabels();
    const byType = /* @__PURE__ */ new Map();
    for (const row of rows) {
      const key = this.plugin.recordTypeKeyForTypeName(row.type) || row.type;
      if (!byType.has(key)) byType.set(key, []);
      byType.get(key).push(row);
    }
    for (const typeKey of this.plugin.recordTypeKeys()) {
      const group = byType.get(typeKey);
      if (!group || !group.length) continue;
      this.openItemsEl.createEl("div", {
        cls: `aceto-mm-open-items-group-label aceto-type-marker-${typeKey}`,
        text: `${labels[typeKey] || typeKey} (${group.length})`
      });
      for (const row of group) this.renderOpenItemRow(this.openItemsEl, row);
    }
  }
  renderOpenItemRow(container, row) {
    const rowEl = container.createDiv({ cls: "aceto-mm-open-item" });
    const checkbox = rowEl.createEl("input", { attr: { type: "checkbox" } });
    checkbox.addEventListener("change", () => void this.completeOpenItem(row));
    const text = rowEl.createEl("span", { cls: "aceto-mm-open-item-text", text: row.sentence });
    text.addEventListener("click", () => void this.openSourceForItem(row));
  }
  async completeOpenItem(row) {
    await this.plugin.completeRecord(row.file);
    this.renderOpenItems();
    this.refreshCounters();
  }
  async openSourceForItem(row) {
    const sourceFile = this.app.vault.getAbstractFileByPath(row.sourcePath);
    if (!(sourceFile instanceof import_obsidian.TFile)) return;
    const typeKey = this.plugin.recordTypeKeyForTypeName(row.type);
    const content = await this.app.vault.cachedRead(sourceFile);
    const line = this.plugin.findSourceLineNumber(content, typeKey, row.sentence);
    const leaf = this.app.workspace.getLeaf();
    if (line >= 0) {
      await leaf.openFile(sourceFile, { eState: { line, focus: true } });
    } else {
      await leaf.openFile(sourceFile);
    }
  }
};

// src/meetingMode/markerColorExtension.ts
var import_state2 = require("@codemirror/state");
var import_view2 = require("@codemirror/view");
var recordMarkerColors = import_state2.Facet.define({
  combine: (values) => values[0] || []
});
function buildDecorations(view) {
  const colors = view.state.facet(recordMarkerColors);
  if (!colors.length) return import_view2.Decoration.none;
  const byType = new Map(colors.map((c) => [c.type, c.className]));
  const pattern = new RegExp(`^(\\s*(?:[-*+]\\s*)?)(${colors.map((c) => c.type).join("|")})(::)`, "i");
  const builder = new import_state2.RangeSetBuilder();
  for (const { from, to } of view.visibleRanges) {
    let pos = from;
    while (pos <= to) {
      const line = view.state.doc.lineAt(pos);
      const match = line.text.match(pattern);
      if (match) {
        const type = match[2].toLowerCase();
        const className = byType.get(type);
        if (className) {
          const startOffset = line.from + match[1].length;
          const endOffset = startOffset + match[2].length + match[3].length;
          builder.add(startOffset, endOffset, import_view2.Decoration.mark({ class: className }));
        }
      }
      if (line.to >= view.state.doc.length) break;
      pos = line.to + 1;
    }
  }
  return builder.finish();
}
var recordMarkerHighlightPlugin = import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = buildDecorations(view);
    }
    update(update) {
      if (update.docChanged || update.viewportChanged) {
        this.decorations = buildDecorations(update.view);
      }
    }
  },
  { decorations: (v) => v.decorations }
);

// src/meetingMode/markerReadingViewProcessor.ts
function highlightRecordMarkersInElement(el, typeKeys) {
  var _a;
  if (!typeKeys.length) return;
  const pattern = new RegExp(`^(\\s*)(${typeKeys.join("|")})(::)`, "i");
  const containers = [];
  if ((_a = el.matches) == null ? void 0 : _a.call(el, "p, li")) containers.push(el);
  containers.push(...Array.from(el.querySelectorAll("p, li")));
  for (const container of containers) {
    let atLineStart = true;
    for (const node of Array.from(container.childNodes)) {
      if (node.nodeType === Node.ELEMENT_NODE && node.tagName === "BR") {
        atLineStart = true;
        continue;
      }
      if (!atLineStart) continue;
      atLineStart = false;
      if (node.nodeType !== Node.TEXT_NODE) continue;
      const text = node.textContent || "";
      const match = text.match(pattern);
      if (!match) continue;
      const type = match[2].toLowerCase();
      const leadLen = match[1].length;
      const markerLen = match[2].length + match[3].length;
      const before = text.slice(0, leadLen);
      const marker = text.slice(leadLen, leadLen + markerLen);
      const after = text.slice(leadLen + markerLen);
      const span = document.createElement("span");
      span.className = `aceto-type-marker-${type}`;
      span.textContent = marker;
      const parent = node.parentNode;
      if (!parent) continue;
      parent.insertBefore(document.createTextNode(before), node);
      parent.insertBefore(span, node);
      parent.insertBefore(document.createTextNode(after), node);
      parent.removeChild(node);
    }
  }
}

// src/main.ts
var DEFAULT_SETTINGS = {
  peopleFolder: "98.Knowledge/People",
  personTemplatePath: "99.System/Templates/Template, Person.md",
  executiveFolder: "12. \u{1F3AF} Executive",
  decisionsFolder: "16. \u2696\uFE0F Decisions",
  risksFolder: "17. \u26A0\uFE0F Risks",
  issuesFolder: "18. \u{1F6A7} Issues",
  actionsFolder: "19. \u2705 Actions",
  dashboardFolder: "01.Home/Dashboards",
  dashboardBaseName: "00.\u{1F39B}\uFE0F Master",
  autoSync: false,
  autoCreatePeople: false,
  debounceMs: 1800,
  excludedFolders: ["99.System/Templates"],
  excludedHeadings: ["links", "backlinks", "references", "related", "carry forward", "same day"],
  autoLinkTypes: { project: "project", program: "program", capability: "capability", meeting: "meeting" },
  priorityEnabled: false,
  priorityLevels: ["None", "Low", "Medium", "High"],
  yourPersonNote: "",
  meetingModeAutoOpen: false,
  meetingModeRememberOwner: true,
  meetingModeRememberCategory: true,
  meetingModeShowCounters: true,
  meetingModeFocusAfterSave: true,
  lastOwnerPath: "",
  lastCapturePrefix: ""
};
var RECORD_TYPES = {
  d: { key: "decisions", singular: "Decision", heading: "Decisions", typeName: "decision", folderSetting: "decisionsFolder" },
  r: { key: "risks", singular: "Risk", heading: "Risks", typeName: "risk", folderSetting: "risksFolder" },
  i: { key: "issues", singular: "Issue", heading: "Issues", typeName: "issue", folderSetting: "issuesFolder" },
  e: { key: "executive_follow_ups", singular: "Executive Follow-up", heading: "Executive Follow-ups", typeName: "executive-follow-up", folderSetting: "executiveFolder" },
  a: { key: "actions", singular: "Action", heading: "Actions", typeName: "action", folderSetting: "actionsFolder" }
};
var RECORD_TYPE_PATTERN = Object.keys(RECORD_TYPES).join("|");
var REQUIRED_PLUGINS = [
  { id: "dataview", name: "Dataview" },
  { id: "obsidian-tasks-plugin", name: "Tasks" },
  { id: "templater-obsidian", name: "Templater" },
  { id: "obsidian-meta-bind-plugin", name: "Meta Bind" }
];
var EnvironmentValidationModal = class extends import_obsidian2.Modal {
  constructor(app, results) {
    super(app);
    this.results = results;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("aceto-environment-validation");
    contentEl.createEl("h2", { text: "ACE2X Environment Validator" });
    const issueCount = this.results.filter((result) => !result.ok).length;
    contentEl.createEl("p", {
      text: issueCount ? `ACE2X found ${issueCount} configuration item${issueCount === 1 ? "" : "s"} requiring attention.` : "ACE2X environment is ready."
    });
    const list = contentEl.createDiv({ cls: "aceto-validation-results" });
    for (const result of this.results) {
      const row = list.createDiv({ cls: `aceto-validation-result ${result.ok ? "is-ready" : "needs-attention"}` });
      row.createEl("strong", { text: `${result.ok ? "\u2713" : "\u26A0"} ${result.label}` });
      row.createEl("div", { text: result.detail });
      if (!result.ok && result.action) {
        row.createEl("div", { cls: "aceto-validation-action", text: `Action: ${result.action}` });
      }
    }
    const actions = contentEl.createDiv({ cls: "aceto-preview-actions" });
    const close = actions.createEl("button", { cls: "mod-cta", text: "Close" });
    close.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var MetadataPreviewModal = class extends import_obsidian2.Modal {
  constructor(app, analysis, onApply) {
    super(app);
    this.analysis = analysis;
    this.onApply = onApply;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("aceto-metadata-preview");
    contentEl.createEl("h2", { text: "Metadata Preview" });
    contentEl.createEl("div", { cls: "aceto-preview-file", text: this.analysis.file.path });
    this.renderSection(contentEl, "People", this.analysis.people.map((x) => x.display));
    this.renderSection(contentEl, "Tags", this.analysis.tags.map((x) => `#${x}`));
    this.renderSection(contentEl, "Decisions", this.analysis.records.filter((x) => x.type === "d").map((x) => x.displayText));
    this.renderSection(contentEl, "Risks", this.analysis.records.filter((x) => x.type === "r").map((x) => x.displayText));
    this.renderSection(contentEl, "Issues", this.analysis.records.filter((x) => x.type === "i").map((x) => x.displayText));
    this.renderSection(contentEl, "Executive Follow-ups", this.analysis.records.filter((x) => x.type === "e").map((x) => x.displayText));
    this.renderSection(contentEl, "Actions", this.analysis.records.filter((x) => x.type === "a").map((x) => x.displayText));
    const changes = [
      `Source metadata: ${this.analysis.sourceWillChange ? "will update" : "no indexed change"}`,
      `Person pages affected: ${this.analysis.affectedPersonPaths.length}`,
      `Unresolved links: ${this.analysis.unresolvedLinks.length}`
    ];
    this.renderSection(contentEl, "Changes", changes);
    if (this.analysis.unresolvedLinks.length) {
      const warning = contentEl.createDiv({ cls: "aceto-preview-warning" });
      warning.createEl("strong", { text: "Unresolved links" });
      warning.createEl("div", { text: this.analysis.unresolvedLinks.map((x) => `[[${x}]]`).join(", ") });
      warning.createEl("div", {
        text: this.analysis.autoCreatePeople ? "These pages will be created as person pages when applied." : "They will remain unresolved. Enable creation in settings only when these links represent people."
      });
    }
    const buttons = contentEl.createDiv({ cls: "aceto-preview-actions" });
    const cancel = buttons.createEl("button", { text: "Cancel" });
    cancel.onclick = () => this.close();
    const apply = buttons.createEl("button", { cls: "mod-cta", text: "Apply" });
    apply.onclick = async () => {
      apply.disabled = true;
      try {
        await this.onApply();
        this.close();
      } catch (error) {
        console.error(error);
        new import_obsidian2.Notice(`Metadata sync failed: ${error.message || error}`);
        apply.disabled = false;
      }
    };
  }
  renderSection(parent, title, items) {
    const section = parent.createDiv({ cls: "aceto-preview-section" });
    section.createEl("h3", { text: title });
    if (!items.length) {
      section.createEl("div", { cls: "aceto-preview-empty", text: "None" });
      return;
    }
    const list = section.createEl("ul");
    for (const item of items) list.createEl("li", { text: item });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var BatchPreviewModal = class extends import_obsidian2.Modal {
  constructor(app, title, analyses, onApply) {
    super(app);
    this.title = title;
    this.analyses = analyses;
    this.onApply = onApply;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("aceto-metadata-preview");
    contentEl.createEl("h2", { text: this.title });
    const totals = this.analyses.reduce((a, x) => {
      a.tags += x.tags.length;
      a.people += x.people.length;
      a.decisions += x.records.filter((r) => r.type === "d").length;
      a.risks += x.records.filter((r) => r.type === "r").length;
      a.issues += x.records.filter((r) => r.type === "i").length;
      a.executive += x.records.filter((r) => r.type === "e").length;
      a.actions += x.records.filter((r) => r.type === "a").length;
      a.unresolved += x.unresolvedLinks.length;
      return a;
    }, { tags: 0, people: 0, decisions: 0, risks: 0, issues: 0, executive: 0, actions: 0, unresolved: 0 });
    const list = contentEl.createEl("ul");
    list.createEl("li", { text: `Notes: ${this.analyses.length}` });
    list.createEl("li", { text: `People references: ${totals.people}` });
    list.createEl("li", { text: `Decisions: ${totals.decisions}` });
    list.createEl("li", { text: `Risks: ${totals.risks}` });
    list.createEl("li", { text: `Issues: ${totals.issues}` });
    list.createEl("li", { text: `Executive follow-ups: ${totals.executive}` });
    list.createEl("li", { text: `Actions: ${totals.actions}` });
    list.createEl("li", { text: `Tags: ${totals.tags}` });
    if (totals.unresolved) list.createEl("li", { text: `Unresolved links: ${totals.unresolved}` });
    const buttons = contentEl.createDiv({ cls: "aceto-preview-actions" });
    const cancel = buttons.createEl("button", { text: "Cancel" });
    cancel.onclick = () => this.close();
    const apply = buttons.createEl("button", { cls: "mod-cta", text: "Apply" });
    apply.onclick = async () => {
      apply.disabled = true;
      try {
        await this.onApply();
        this.close();
      } catch (error) {
        console.error(error);
        new import_obsidian2.Notice(`Metadata sync failed: ${error.message || error}`);
        apply.disabled = false;
      }
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ACE2XKnowledgeOSPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    let saved = await this.loadData() || {};
    if (!Object.keys(saved).length) saved = await this.loadLegacyPluginData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved.settings || saved);
    this.index = saved.index || {};
    this.processingPaths = /* @__PURE__ */ new Set();
    this.lastTransaction = null;
    this.syncDebounced = (0, import_obsidian2.debounce)(async (file) => {
      if (file instanceof import_obsidian2.TFile) await this.syncFile(file, false);
    }, this.settings.debounceMs, true);
    this.recordStatusDebounced = (0, import_obsidian2.debounce)(async (file) => {
      if (file instanceof import_obsidian2.TFile) await this.syncRecordStatusToSource(file);
    }, this.settings.debounceMs, true);
    this.addRibbonIcon("refresh-cw", "Preview knowledge sync", () => this.previewCurrentNote());
    this.addCommand({ id: "analyze-current-note", name: "Analyze current note", callback: () => this.previewCurrentNote() });
    this.addCommand({ id: "sync-current-note", name: "Sync current note", callback: () => this.previewCurrentNote() });
    this.addCommand({ id: "sync-current-folder", name: "Sync current folder", callback: () => this.previewCurrentFolder() });
    this.addCommand({ id: "sync-entire-vault", name: "Sync entire vault", callback: () => this.previewEntireVault() });
    this.addCommand({ id: "sync-knowledge-os-status-changes", name: "Sync Knowledge OS Status Changes", callback: async () => {
      await this.syncKnowledgeOSStatusChanges();
    } });
    this.addCommand({ id: "auto-detect-folders", name: "Auto-detect configured folders", callback: async () => {
      const changed = await this.autoDetectFolders();
      new import_obsidian2.Notice(changed ? "Knowledge OS folder locations updated." : "No better folder matches were found.");
    } });
    this.addCommand({ id: "validate-ace2x-environment", name: "Validate ACE2X environment", callback: () => {
      this.showEnvironmentValidation();
    } });
    this.addCommand({ id: "undo-last-sync", name: "Undo last sync", checkCallback: (checking) => {
      if (!this.lastTransaction) return false;
      if (!checking) this.undoLastTransaction();
      return true;
    } });
    this.registerEvent(this.app.vault.on("rename", async (file, oldPath) => {
      if (!(file instanceof import_obsidian2.TFolder)) return;
      const changed = this.updateConfiguredPathsAfterFolderRename(oldPath, file.path);
      if (changed) {
        await this.persist();
        new import_obsidian2.Notice("Knowledge OS folder settings updated after folder rename.");
      }
    }));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (!(file instanceof import_obsidian2.TFile)) return;
      if (this.processingPaths.has(file.path)) return;
      if (this.isPersonFile(file)) return;
      if (this.isManagedRecordFile(file) || this.isManagedRecordPath(file)) {
        this.recordStatusDebounced(file);
        return;
      }
      if (this.settings.autoSync && this.shouldProcess(file)) this.syncDebounced(file);
    }));
    this.registerView(VIEW_TYPE_MEETING_MODE, (leaf) => new MeetingModeView(leaf, this));
    this.registerEditorExtension(highlightLinesField);
    this.registerEditorExtension([
      recordMarkerColors.of(Object.keys(RECORD_TYPES).map((key) => ({ type: key, className: `aceto-type-marker-${key}` }))),
      recordMarkerHighlightPlugin
    ]);
    this.registerMarkdownPostProcessor((el) => highlightRecordMarkersInElement(el, this.recordTypeKeys()));
    this.addRibbonIcon("target", "Toggle Meeting Mode panel", () => this.toggleMeetingModeView());
    this.addCommand({ id: "start-executive-meeting-mode", name: "Start Executive Meeting Mode", callback: () => this.activateMeetingModeView() });
    this.addCommand({ id: "stop-executive-meeting-mode", name: "Stop Executive Meeting Mode", callback: () => this.deactivateMeetingModeView() });
    this.addCommand({ id: "toggle-meeting-panel", name: "Toggle Meeting Panel", callback: () => this.toggleMeetingModeView() });
    this.addCommand({ id: "capture-executive-follow-up", name: "Capture Executive Follow-up", callback: () => this.activateMeetingModeView("e") });
    this.addCommand({ id: "capture-risk", name: "Capture Risk", callback: () => this.activateMeetingModeView("r") });
    this.addCommand({ id: "capture-issue", name: "Capture Issue", callback: () => this.activateMeetingModeView("i") });
    this.addCommand({ id: "capture-decision", name: "Capture Decision", callback: () => this.activateMeetingModeView("d") });
    this.addCommand({ id: "capture-action", name: "Capture Action", callback: () => this.activateMeetingModeView("a") });
    this.registerEvent(this.app.workspace.on("file-open", (file) => {
      var _a;
      if (!this.settings.meetingModeAutoOpen) return;
      if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md") return;
      const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
      const hasField = (value) => Array.isArray(value) ? value.length > 0 : Boolean(value);
      if (hasField(fm == null ? void 0 : fm.participants) || hasField(fm == null ? void 0 : fm.owner)) {
        this.activateMeetingModeView();
      }
    }));
    this.addSettingTab(new ACE2XKnowledgeOSSettingTab(this.app, this));
  }
  onunload() {
    var _a, _b;
    if ((_a = this.syncDebounced) == null ? void 0 : _a.cancel) this.syncDebounced.cancel();
    if ((_b = this.recordStatusDebounced) == null ? void 0 : _b.cancel) this.recordStatusDebounced.cancel();
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_MEETING_MODE);
  }
  async activateMeetingModeView(prefill = null) {
    var _a;
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_MEETING_MODE)[0];
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_MEETING_MODE, active: true });
    }
    workspace.revealLeaf(leaf);
    if (prefill && ((_a = leaf.view) == null ? void 0 : _a.setPrefill)) leaf.view.setPrefill(prefill);
  }
  deactivateMeetingModeView() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_MEETING_MODE);
  }
  async toggleMeetingModeView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_MEETING_MODE)[0];
    if (existing) this.deactivateMeetingModeView();
    else await this.activateMeetingModeView();
  }
  validateEnvironment() {
    var _a, _b;
    const installedPlugins = ((_a = this.app.plugins) == null ? void 0 : _a.manifests) || {};
    const enabledPlugins = ((_b = this.app.plugins) == null ? void 0 : _b.enabledPlugins) || /* @__PURE__ */ new Set();
    const results = [];
    for (const plugin of REQUIRED_PLUGINS) {
      const installed = Boolean(installedPlugins[plugin.id]);
      const enabled = enabledPlugins.has(plugin.id);
      results.push({
        category: "plugin",
        label: plugin.name,
        ok: installed && enabled,
        detail: !installed ? "Required community plugin is not installed." : enabled ? "Installed and enabled." : "Installed but currently disabled.",
        action: !installed ? `Install ${plugin.name} from Obsidian Community plugins.` : enabled ? "" : `Enable ${plugin.name} in Community plugins.`
      });
    }
    const folderLabels = {
      peopleFolder: "People folder",
      executiveFolder: "Executive follow-up folder",
      decisionsFolder: "Decisions folder",
      risksFolder: "Risks folder",
      issuesFolder: "Issues folder",
      actionsFolder: "Actions folder",
      dashboardFolder: "Dashboard folder"
    };
    for (const key of this.folderSettingKeys()) {
      const configured = (0, import_obsidian2.normalizePath)(this.settings[key] || "");
      const exists = configured && this.app.vault.getAbstractFileByPath(configured) instanceof import_obsidian2.TFolder;
      results.push({
        category: "folder",
        label: folderLabels[key] || key,
        ok: Boolean(exists),
        detail: exists ? `Configured: ${configured}` : configured ? `Configured location is missing: ${configured}` : "No folder has been selected.",
        action: exists ? "" : "Select an existing folder in ACE2X settings or run Auto-detect folders."
      });
    }
    const templatePath = (0, import_obsidian2.normalizePath)(this.settings.personTemplatePath || "");
    const template = templatePath ? this.app.vault.getAbstractFileByPath(templatePath) : null;
    results.push({
      category: "template",
      label: "Person template",
      ok: template instanceof import_obsidian2.TFile,
      detail: template instanceof import_obsidian2.TFile ? `Configured: ${templatePath}` : templatePath ? `Configured template is missing: ${templatePath}` : "No person template has been selected.",
      action: template instanceof import_obsidian2.TFile ? "" : "Select an existing person template in ACE2X settings."
    });
    const dashboardName = String(this.settings.dashboardBaseName || "").trim().replace(/\.base$/i, "");
    results.push({
      category: "dashboard",
      label: "Dashboard Base name",
      ok: Boolean(dashboardName),
      detail: dashboardName ? `Configured: ${dashboardName}.base` : "No dashboard Base name is configured.",
      action: dashboardName ? "" : "Enter a dashboard Base name in ACE2X settings."
    });
    return results;
  }
  showEnvironmentValidation() {
    const results = this.validateEnvironment();
    const issueCount = results.filter((result) => !result.ok).length;
    new EnvironmentValidationModal(this.app, results).open();
    new import_obsidian2.Notice(
      issueCount ? `ACE2X found ${issueCount} configuration item${issueCount === 1 ? "" : "s"} requiring attention.` : "ACE2X environment is ready."
    );
    return results;
  }
  folderSettingKeys() {
    return ["peopleFolder", "executiveFolder", "decisionsFolder", "risksFolder", "issuesFolder", "actionsFolder", "dashboardFolder"];
  }
  recordTypeKeys() {
    return Object.keys(RECORD_TYPES);
  }
  recordTypeLabels() {
    return Object.fromEntries(Object.entries(RECORD_TYPES).map(([key, definition]) => [key, definition.heading]));
  }
  recordFolderPaths() {
    return Object.values(RECORD_TYPES).map((definition) => (0, import_obsidian2.normalizePath)(this.settings[definition.folderSetting] || "")).filter(Boolean);
  }
  recordTypeKeyForTypeName(typeName) {
    const entry = Object.entries(RECORD_TYPES).find(([, definition]) => definition.typeName === typeName);
    return entry ? entry[0] : null;
  }
  findAllSourceLineNumbers(content, typeKey) {
    if (!typeKey) return [];
    const lines = String(content || "").split("\n");
    const pattern = new RegExp(`^(\\s*(?:[-*+]\\s*)?(${RECORD_TYPE_PATTERN})::\\s*)(.+?)(\\s*)$`, "i");
    const result = [];
    for (let i = 0; i < lines.length; i++) {
      const match = lines[i].match(pattern);
      if (match && match[2].toLowerCase() === typeKey) result.push(i);
    }
    return result;
  }
  findSourceLineNumber(content, typeKey, sentence) {
    if (!typeKey) return -1;
    const canonical = this.canonicalRecordText(sentence);
    const lines = String(content || "").split("\n");
    const pattern = new RegExp(`^(\\s*(?:[-*+]\\s*)?(${RECORD_TYPE_PATTERN})::\\s*)(.+?)(\\s*)$`, "i");
    for (let i = 0; i < lines.length; i++) {
      const match = lines[i].match(pattern);
      if (!match || match[2].toLowerCase() !== typeKey) continue;
      const parsed = this.parseInlineStatus(match[3]);
      if (this.canonicalRecordText(parsed.text) === canonical) return i;
    }
    return -1;
  }
  async completeRecord(recordFile) {
    await this.app.fileManager.processFrontMatter(recordFile, (fm) => {
      fm.status = "Done";
      fm.completed_date = fm.completed_date || this.todayDate();
    });
    await this.syncRecordStatusToSource(recordFile);
  }
  personFilePaths() {
    return this.app.vault.getMarkdownFiles().filter((file) => this.isPersonFile(file)).map((file) => file.path).sort((a, b) => a.localeCompare(b, void 0, { numeric: true, sensitivity: "base" }));
  }
  vaultFolderPaths() {
    return this.app.vault.getAllLoadedFiles().filter((entry) => entry instanceof import_obsidian2.TFolder).map((folder) => (0, import_obsidian2.normalizePath)(folder.path)).filter(Boolean).sort((a, b) => a.localeCompare(b, void 0, { numeric: true, sensitivity: "base" }));
  }
  updateConfiguredPathsAfterFolderRename(oldPath, newPath) {
    oldPath = (0, import_obsidian2.normalizePath)(oldPath || "");
    newPath = (0, import_obsidian2.normalizePath)(newPath || "");
    let changed = false;
    for (const key of this.folderSettingKeys()) {
      const current = (0, import_obsidian2.normalizePath)(this.settings[key] || "");
      if (current === oldPath || current.startsWith(oldPath + "/")) {
        this.settings[key] = (0, import_obsidian2.normalizePath)(newPath + current.slice(oldPath.length));
        changed = true;
      }
    }
    return changed;
  }
  normalizedFolderLabel(path) {
    const name = String(path || "").split("/").pop() || "";
    return name.toLowerCase().replace(/^\d+[. _-]*/, "").replace(/[^a-z0-9]+/g, " ").trim();
  }
  findFolderMatch(terms) {
    var _a;
    const folders = this.vaultFolderPaths();
    const scored = folders.map((path) => {
      const label = this.normalizedFolderLabel(path);
      let score = 0;
      for (const term of terms) {
        if (label === term) score = Math.max(score, 100);
        else if (label.includes(term)) score = Math.max(score, 60);
      }
      if (/archive|template|attachment/i.test(path)) score -= 50;
      return { path, score, depth: path.split("/").length };
    }).filter((item) => item.score > 0);
    scored.sort((a, b) => b.score - a.score || a.depth - b.depth || a.path.localeCompare(b.path));
    return ((_a = scored[0]) == null ? void 0 : _a.path) || "";
  }
  async autoDetectFolders() {
    const mappings = {
      peopleFolder: ["people", "persons", "contacts"],
      executiveFolder: ["executive", "executive follow ups", "leadership"],
      decisionsFolder: ["decisions", "decision"],
      risksFolder: ["risks", "risk register", "risk"],
      issuesFolder: ["issues", "issue register", "issue"],
      actionsFolder: ["actions", "action items"],
      dashboardFolder: ["dashboards", "dashboard", "home"]
    };
    let changed = false;
    for (const [key, terms] of Object.entries(mappings)) {
      const current = (0, import_obsidian2.normalizePath)(this.settings[key] || "");
      const currentExists = current && this.app.vault.getAbstractFileByPath(current) instanceof import_obsidian2.TFolder;
      if (currentExists) continue;
      const match = this.findFolderMatch(terms);
      if (match && match !== current) {
        this.settings[key] = match;
        changed = true;
      }
    }
    if (changed) await this.persist();
    return changed;
  }
  async loadLegacyPluginData() {
    const configDir = this.app.vault.configDir || ".obsidian";
    const candidates = [
      `${configDir}/plugins/aceto-knowledge-os/data.json`,
      `${configDir}/plugins/aceto-metadata-sync/data.json`
    ];
    for (const path of candidates) {
      try {
        if (!await this.app.vault.adapter.exists(path)) continue;
        const parsed = JSON.parse(await this.app.vault.adapter.read(path));
        if (parsed && typeof parsed === "object") return parsed;
      } catch (error) {
        console.warn("ACE2X Knowledge OS could not migrate legacy settings", path, error);
      }
    }
    return {};
  }
  async persist() {
    await this.saveData({ settings: this.settings, index: this.index });
  }
  isManagedRecordFile(file) {
    var _a;
    if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md") return false;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (!(fm == null ? void 0 : fm.record_id) || !(fm == null ? void 0 : fm.source_path)) return false;
    return Object.values(RECORD_TYPES).some((definition) => fm.type === definition.typeName);
  }
  isManagedRecordPath(file) {
    if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md") return false;
    const path = (0, import_obsidian2.normalizePath)(file.path);
    return Object.values(RECORD_TYPES).some((definition) => {
      const folder = (0, import_obsidian2.normalizePath)(this.settings[definition.folderSetting] || "");
      return folder && path.startsWith(folder + "/");
    });
  }
  normalizedStatus(value) {
    const raw = String(value || "open").trim().toLowerCase();
    if (["d", "c", "done", "closed", "complete", "completed", "resolved"].includes(raw)) return "Done";
    return "Open";
  }
  statusIsClosed(value) {
    return this.normalizedStatus(value) === "Done";
  }
  parseInlineStatus(text) {
    const raw = String(text || "").trim();
    const unstruck = raw.replace(/^~~|~~$/g, "").trim();
    const doneMatch = unstruck.match(/(?:^|\s)done::\s*(\d{4}-\d{2}-\d{2})(?=\s|$)/i);
    const statusMatch = unstruck.match(/(?:^|\s)s::\s*(.*?)(?=\s+done::|$)/i);
    let body = unstruck;
    if (statusMatch) body = body.slice(0, statusMatch.index).trim();
    else if (doneMatch) body = `${body.slice(0, doneMatch.index)} ${body.slice(doneMatch.index + doneMatch[0].length)}`.trim();
    const struck = /^~~[\s\S]*~~$/.test(raw);
    return {
      text: body,
      status: this.normalizedStatus(statusMatch ? statusMatch[1].trim() || "open" : struck ? "done" : "open"),
      explicit: Boolean(statusMatch),
      doneDate: doneMatch ? doneMatch[1] : ""
    };
  }
  todayDate() {
    const now = /* @__PURE__ */ new Date();
    const local = new Date(now.getTime() - now.getTimezoneOffset() * 6e4);
    return local.toISOString().slice(0, 10);
  }
  withInlineStatus(text, status, requestedDoneDate = "") {
    const parsed = this.parseInlineStatus(text);
    const body = parsed.text.trim().replace(/^~~|~~$/g, "");
    const normalized = this.statusIsClosed(status) ? "Done" : "Open";
    if (normalized === "Done") {
      const doneDate = requestedDoneDate || parsed.doneDate || this.todayDate();
      return `~~${body} s::d done::${doneDate}~~`;
    }
    return `${body} s::o`;
  }
  shouldProcess(file) {
    if (!(file instanceof import_obsidian2.TFile) || file.extension !== "md") return false;
    const path = (0, import_obsidian2.normalizePath)(file.path);
    const peopleFolder = (0, import_obsidian2.normalizePath)(this.settings.peopleFolder);
    if (path === peopleFolder || path.startsWith(peopleFolder + "/")) return false;
    const managedFolders = [this.settings.executiveFolder, this.settings.decisionsFolder, this.settings.risksFolder, this.settings.issuesFolder, this.settings.actionsFolder].map((folder) => (0, import_obsidian2.normalizePath)(folder || "")).filter(Boolean);
    if (managedFolders.some((folder) => path === folder || path.startsWith(folder + "/"))) return false;
    return !(this.settings.excludedFolders || []).some((folder) => {
      const normalized = (0, import_obsidian2.normalizePath)(folder.trim());
      return normalized && (path === normalized || path.startsWith(normalized + "/"));
    });
  }
  async previewCurrentNote() {
    const file = this.app.workspace.getActiveFile();
    if (!file) return new import_obsidian2.Notice("No active note.");
    if (!this.shouldProcess(file)) return new import_obsidian2.Notice("This note is excluded from knowledge sync.");
    const analysis = await this.analyzeFile(file);
    new MetadataPreviewModal(this.app, analysis, async () => {
      this.beginTransaction(`Sync ${file.basename}`);
      const result = await this.applyAnalysis(analysis);
      await this.persist();
      new import_obsidian2.Notice(`Synced ${result.decisions} decisions, ${result.risks} risks, ${result.issues} issues, ${result.executive} executive follow-ups and ${result.actions} actions.`);
    }).open();
  }
  async previewCurrentFolder() {
    var _a;
    const active = this.app.workspace.getActiveFile();
    if (!active) return new import_obsidian2.Notice("No active note.");
    const folder = ((_a = active.parent) == null ? void 0 : _a.path) || "";
    const files = this.app.vault.getMarkdownFiles().filter((f) => {
      var _a2;
      return this.shouldProcess(f) && (((_a2 = f.parent) == null ? void 0 : _a2.path) || "") === folder;
    });
    await this.previewBatch(`Sync folder: ${folder || "Vault root"}`, files);
  }
  async previewEntireVault() {
    await this.previewBatch("Sync entire vault", this.app.vault.getMarkdownFiles().filter((f) => this.shouldProcess(f)));
  }
  async previewBatch(title, files) {
    if (!files.length) return new import_obsidian2.Notice("No eligible notes found.");
    const analyses = [];
    for (const file of files) analyses.push(await this.analyzeFile(file));
    new BatchPreviewModal(this.app, title, analyses, async () => {
      this.beginTransaction(title);
      for (const analysis of analyses) {
        await this.applyAnalysis(analysis);
      }
      await this.persist();
      new import_obsidian2.Notice(`Sync complete: ${analyses.length} notes processed.`);
    }).open();
  }
  beginTransaction(label) {
    this.lastTransaction = { label, files: /* @__PURE__ */ new Map() };
  }
  async captureBefore(file) {
    if (!this.lastTransaction || this.lastTransaction.files.has(file.path)) return;
    this.lastTransaction.files.set(file.path, await this.app.vault.read(file));
  }
  async undoLastTransaction() {
    if (!this.lastTransaction) return new import_obsidian2.Notice("Nothing to undo.");
    const entries = [...this.lastTransaction.files.entries()].reverse();
    for (const [path, content] of entries) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (content === null) {
        if (file instanceof import_obsidian2.TFile) await this.app.vault.delete(file);
        continue;
      }
      if (file instanceof import_obsidian2.TFile) {
        this.processingPaths.add(path);
        await this.app.vault.modify(file, content);
        this.processingPaths.delete(path);
      }
    }
    const count = entries.length;
    this.lastTransaction = null;
    new import_obsidian2.Notice(`Undo complete: restored ${count} files.`);
  }
  async analyzeFile(file) {
    const content = await this.app.vault.cachedRead(file);
    const scoped = this.removeExcludedSections(content);
    const records = this.extractRecords(scoped, file);
    const scanContent = this.stripIgnoredContent(scoped);
    const tags = this.extractTags(scanContent);
    const people = this.extractResolvedPeople(scoped, file);
    const unresolvedLinks = [...new Set(records.flatMap((r) => r.unresolvedLinks))].sort();
    const affectedPersonPaths = [...new Set(records.flatMap((r) => r.people.map((p) => p.path)))];
    const signature = JSON.stringify({
      tags,
      people: people.map((p) => p.path),
      records: records.map((r) => ({ id: r.id, type: r.type, text: r.text, people: r.people.map((p) => p.path), unresolved: r.unresolvedLinks }))
    });
    const indexed = this.index[file.path];
    return {
      file,
      content,
      tags,
      people,
      records,
      unresolvedLinks,
      affectedPersonPaths,
      autoCreatePeople: this.settings.autoCreatePeople,
      signature,
      sourceWillChange: !indexed || indexed.signature !== signature
    };
  }
  async syncFile(file, showNotice = false) {
    const analysis = await this.analyzeFile(file);
    this.beginTransaction(`Automatic sync ${file.basename}`);
    const result = await this.applyAnalysis(analysis);
    await this.persist();
    if (showNotice) new import_obsidian2.Notice(`Synced ${result.decisions} decisions, ${result.risks} risks, ${result.issues} issues, ${result.executive} executive follow-ups and ${result.actions} actions.`);
  }
  async applyAnalysis(initialAnalysis) {
    const file = initialAnalysis.file;
    if (this.processingPaths.has(file.path)) return { decisions: 0, risks: 0, issues: 0, executive: 0, personFiles: 0 };
    this.processingPaths.add(file.path);
    try {
      if (this.settings.autoCreatePeople) {
        for (const target of initialAnalysis.unresolvedLinks) await this.createPersonFile(target);
      }
      const analysis = this.settings.autoCreatePeople && initialAnalysis.unresolvedLinks.length ? await this.analyzeFile(file) : initialAnalysis;
      await this.captureBefore(file);
      await this.updateSourceFrontmatter(file, analysis);
      const sourceDate = this.getSourceDate(file);
      const sourceLink = `[[${file.path.replace(/\.md$/i, "")}|${file.basename}]]`;
      const personFiles = 0;
      await this.syncRecordNotes(analysis.records, file, sourceLink, sourceDate);
      await this.ensureKnowledgeBase();
      this.index[file.path] = {
        signature: analysis.signature,
        syncedAt: (/* @__PURE__ */ new Date()).toISOString(),
        tags: analysis.tags,
        people: analysis.people.map((p) => p.path),
        records: analysis.records.map((r) => ({ id: r.id, type: r.type, text: r.text, displayText: r.displayText, people: r.people.map((p) => p.path) }))
      };
      return {
        decisions: analysis.records.filter((r) => r.type === "d").length,
        risks: analysis.records.filter((r) => r.type === "r").length,
        issues: analysis.records.filter((r) => r.type === "i").length,
        executive: analysis.records.filter((r) => r.type === "e").length,
        actions: analysis.records.filter((r) => r.type === "a").length,
        personFiles
      };
    } finally {
      this.processingPaths.delete(file.path);
    }
  }
  cleanHeading(text) {
    return text.replace(/[#]+$/, "").replace(/[^\p{L}\p{N}\s-]/gu, "").replace(/\s+/g, " ").trim().toLowerCase();
  }
  removeExcludedSections(text) {
    const lines = text.split("\n");
    const kept = [];
    let excluding = false;
    let excludedLevel = null;
    const excluded = (this.settings.excludedHeadings || []).map((x) => x.toLowerCase().trim());
    for (const line of lines) {
      const match = line.match(/^\s*(#{1,6})\s+(.+?)\s*$/);
      if (match) {
        const level = match[1].length;
        const heading = this.cleanHeading(match[2]);
        if (excluded.some((x) => heading.startsWith(x))) {
          excluding = true;
          excludedLevel = level;
          continue;
        }
        if (excluding && level <= excludedLevel) {
          excluding = false;
          excludedLevel = null;
        }
      }
      if (!excluding) kept.push(line);
    }
    return kept.join("\n");
  }
  stripIgnoredContent(text) {
    return text.replace(/^---\n[\s\S]*?\n---\n?/m, "").replace(/```[\s\S]*?```/g, "").replace(/`[^`]*`/g, "").replace(/https?:\/\/\S+/g, "").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").replace(/!\[\[.*?\]\]/g, "").replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2").replace(/\[\[([^\]]+)\]\]/g, "$1");
  }
  extractTags(text) {
    return [...new Set((text.match(/#[\p{L}\p{N}_/-]+/gu) || []).map((x) => x.slice(1)))].sort();
  }
  parseWikiLinks(text) {
    const links = [];
    const regex = /(?<!!)\[\[([^\]]+)\]\]/g;
    let match;
    while ((match = regex.exec(text)) !== null) {
      const raw = match[1].trim();
      const [targetPart, alias] = raw.split("|");
      const target = targetPart.split("#")[0].trim();
      if (target) links.push({ target, alias: (alias == null ? void 0 : alias.trim()) || null, raw: match[0] });
    }
    return links;
  }
  isPersonFile(file) {
    var _a, _b;
    if (!(file instanceof import_obsidian2.TFile)) return false;
    const folder = (0, import_obsidian2.normalizePath)(this.settings.peopleFolder);
    const inPeopleFolder = file.path === folder || file.path.startsWith(folder + "/");
    const type = (_b = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.type;
    return inPeopleFolder || String(type || "").toLowerCase() === "person";
  }
  resolvePersonLink(link, sourceFile) {
    const destination = this.app.metadataCache.getFirstLinkpathDest(link.target, sourceFile.path);
    if (!(destination instanceof import_obsidian2.TFile) || !this.isPersonFile(destination)) return null;
    return {
      path: destination.path,
      basename: destination.basename,
      display: link.alias || link.target,
      canonicalLink: `[[${destination.path.replace(/\.md$/i, "")}|${link.alias || link.target}]]`
    };
  }
  extractResolvedPeople(text, sourceFile) {
    const byPath = /* @__PURE__ */ new Map();
    for (const link of this.parseWikiLinks(text)) {
      const person = this.resolvePersonLink(link, sourceFile);
      if (person && !byPath.has(person.path)) byPath.set(person.path, person);
    }
    return [...byPath.values()].sort((a, b) => a.basename.localeCompare(b.basename));
  }
  resolveTypedLink(link, sourceFile, typeName) {
    var _a, _b;
    const destination = this.app.metadataCache.getFirstLinkpathDest(link.target, sourceFile.path);
    if (!(destination instanceof import_obsidian2.TFile)) return null;
    const fmType = String(((_b = (_a = this.app.metadataCache.getFileCache(destination)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.type) || "").toLowerCase();
    if (fmType !== typeName) return null;
    return {
      path: destination.path,
      basename: destination.basename,
      display: link.alias || link.target,
      canonicalLink: `[[${destination.path.replace(/\.md$/i, "")}|${link.alias || link.target}]]`
    };
  }
  extractResolvedByType(text, sourceFile, typeName) {
    const byPath = /* @__PURE__ */ new Map();
    for (const link of this.parseWikiLinks(text)) {
      const resolved = this.resolveTypedLink(link, sourceFile, typeName);
      if (resolved && !byPath.has(resolved.path)) byPath.set(resolved.path, resolved);
    }
    return [...byPath.values()].sort((a, b) => a.basename.localeCompare(b.basename));
  }
  cleanGeneratedText(text) {
    const parsed = this.parseInlineStatus(text);
    const struck = this.statusIsClosed(parsed.status) || /^~~[\s\S]*~~$/.test(parsed.text.trim());
    let value = parsed.text.trim().replace(/^~~|~~$/g, "");
    value = value.replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2").replace(/\[\[([^\]]+)\]\]/g, (_, target) => target.split("/").pop()).replace(/#([\p{L}\p{N}_/-]+)/gu, "$1").replace(/\s+/g, " ").trim();
    return struck ? `~~${value}~~` : value;
  }
  trailingRecordTags(text) {
    const unstruck = this.parseInlineStatus(text).text.trim().replace(/^~~|~~$/g, "");
    const match = unstruck.match(/((?:\s+#[\p{L}\p{N}_/-]+)+)\s*$/u);
    if (!match) return [];
    return [...match[1].matchAll(/#([\p{L}\p{N}_/-]+)/gu)].map((x) => x[1]);
  }
  personRecordDisplayText(text) {
    const parsed = this.parseInlineStatus(text);
    const struck = this.statusIsClosed(parsed.status) || /^~~[\s\S]*~~$/.test(parsed.text.trim());
    const clean = this.cleanGeneratedText(text).replace(/^~~|~~$/g, "");
    const tags = this.trailingRecordTags(text);
    const value = tags.length ? `${clean} ${tags.join(" ")}` : clean;
    return struck ? `~~${value}~~` : value;
  }
  canonicalRecordText(text) {
    return this.cleanGeneratedText(text).replace(/^~~|~~$/g, "").toLowerCase();
  }
  makeRecordId(sourcePath, type, text, occurrence) {
    const input = `${sourcePath}|${type}|${this.canonicalRecordText(text)}|${occurrence}`;
    let hash = 2166136261;
    for (let i = 0; i < input.length; i++) {
      hash ^= input.charCodeAt(i);
      hash = Math.imul(hash, 16777619);
    }
    return `akos-${(hash >>> 0).toString(36)}`;
  }
  extractRecords(text, sourceFile) {
    const records = [];
    const occurrences = /* @__PURE__ */ new Map();
    const autoLinkTypes = this.settings.autoLinkTypes || {};
    for (const line of text.split("\n")) {
      const match = line.match(new RegExp(`^\\s*(?:[-*+]\\s*)?(${RECORD_TYPE_PATTERN})::\\s*(.+?)\\s*$`, "i"));
      if (!match) continue;
      const type = match[1].toLowerCase();
      const parsedStatus = this.parseInlineStatus(match[2]);
      const recordText = parsedStatus.text.replace(/\s+/g, " ").trim();
      if (!recordText) continue;
      const peopleByPath = /* @__PURE__ */ new Map();
      const typedLinksByField = {};
      for (const field of Object.keys(autoLinkTypes)) typedLinksByField[field] = /* @__PURE__ */ new Map();
      const unresolvedLinks = [];
      for (const link of this.parseWikiLinks(recordText)) {
        const destination = this.app.metadataCache.getFirstLinkpathDest(link.target, sourceFile.path);
        if (!destination) {
          unresolvedLinks.push(link.target);
          continue;
        }
        if (this.isPersonFile(destination)) {
          const person = this.resolvePersonLink(link, sourceFile);
          if (person) peopleByPath.set(person.path, person);
          continue;
        }
        for (const [field, typeName] of Object.entries(autoLinkTypes)) {
          const resolved = this.resolveTypedLink(link, sourceFile, typeName);
          if (resolved) {
            typedLinksByField[field].set(resolved.path, resolved);
            break;
          }
        }
      }
      const occurrenceKey = `${type}|${this.canonicalRecordText(recordText)}`;
      const occurrence = (occurrences.get(occurrenceKey) || 0) + 1;
      occurrences.set(occurrenceKey, occurrence);
      records.push({
        id: this.makeRecordId(sourceFile.path, type, recordText, occurrence),
        type,
        text: recordText,
        status: parsedStatus.status,
        doneDate: parsedStatus.doneDate,
        displayText: this.cleanGeneratedText(recordText),
        personDisplayText: this.personRecordDisplayText(recordText),
        people: [...peopleByPath.values()],
        typedLinks: Object.fromEntries(Object.entries(typedLinksByField).map(([field, byPath]) => [field, [...byPath.values()]])),
        unresolvedLinks
      });
    }
    return records;
  }
  normalizeArray(value) {
    return Array.isArray(value) ? value.map(String) : value == null || value === "" ? [] : [String(value)];
  }
  async updateSourceFrontmatter(file, analysis) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm.tags = [.../* @__PURE__ */ new Set([...this.normalizeArray(fm.tags), ...analysis.tags])];
      fm.people = analysis.people.map((p) => `[[${p.basename}]]`);
      for (const [type, definition] of Object.entries(RECORD_TYPES)) {
        const values = analysis.records.filter((r) => r.type === type).map((r) => r.displayText);
        if (values.length) fm[definition.key] = values;
        else delete fm[definition.key];
        const flag = `has_${definition.key}`;
        if (values.length) fm[flag] = true;
        else delete fm[flag];
      }
      delete fm.attendees;
      delete fm.unknown_attendees;
      delete fm.decision_required;
      delete fm.decision_proceed;
      delete fm.decision_declined;
      delete fm.has_decisions_old;
    });
  }
  getSourceDate(file) {
    var _a, _b, _c, _d;
    const value = (_b = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.date;
    if (value) {
      const text = String(value).trim();
      const match = text.match(/\b(\d{4}-\d{2}-\d{2})\b/);
      return match ? match[1] : text;
    }
    return ((_c = file.basename.match(/\b(\d{4}-\d{2}-\d{2})\b/)) == null ? void 0 : _c[1]) || ((_d = file.path.match(/\b(\d{4}-\d{2}-\d{2})\b/)) == null ? void 0 : _d[1]) || window.moment(file.stat.ctime).format("YYYY-MM-DD");
  }
  async ensureFolder(path) {
    let current = "";
    for (const part of (0, import_obsidian2.normalizePath)(path).split("/")) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current)) await this.app.vault.createFolder(current);
    }
  }
  safeFileName(name) {
    return name.replace(/[\\/:*?"<>|]/g, "-").replace(/\s+/g, " ").trim();
  }
  async createPersonFile(target) {
    const folder = (0, import_obsidian2.normalizePath)(this.settings.peopleFolder);
    await this.ensureFolder(folder);
    const displayName = this.safeFileName(target.split("/").pop());
    if (!displayName) return;
    const path = (0, import_obsidian2.normalizePath)(`${folder}/${displayName}.md`);
    if (this.app.vault.getAbstractFileByPath(path)) return;
    let content = "---\ntype: person\naliases:\n  - {{name}}\n---\n\n# {{name}}\n";
    const template = this.app.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(this.settings.personTemplatePath));
    if (template instanceof import_obsidian2.TFile) content = await this.app.vault.cachedRead(template);
    content = content.replace(/<%\s*tp\.file\.title\s*%>/g, displayName).replace(/\{\{name\}\}/g, displayName);
    const file = await this.app.vault.create(path, content);
    if (this.lastTransaction) this.lastTransaction.files.set(path, null);
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm.type = "person";
      const aliases = this.normalizeArray(fm.aliases);
      if (!aliases.includes(displayName)) aliases.push(displayName);
      fm.aliases = aliases;
    });
  }
  recordFolder(type) {
    const definition = RECORD_TYPES[type];
    return (0, import_obsidian2.normalizePath)(this.settings[definition.folderSetting]);
  }
  yamlQuote(value) {
    return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  recordFileName(record, date) {
    const clean = this.cleanGeneratedText(record.text).replace(/^~~|~~$/g, "");
    const short = this.safeFileName(clean).slice(0, 72).replace(/[. ]+$/g, "") || RECORD_TYPES[record.type].singular;
    return `${date} - ${short} - ${record.id}.md`;
  }
  buildRecordNote(record, sourceFile, sourceLink, date, existingPriority) {
    var _a;
    const definition = RECORD_TYPES[record.type];
    const sentence = this.cleanGeneratedText(record.text).replace(/^~~|~~$/g, "");
    const closed = this.statusIsClosed(record.status) || /^~~[\s\S]*~~$/.test(record.text.trim());
    const owners = record.people.map((p) => `  - ${this.yamlQuote(`[[${p.basename}]]`)}`);
    const tags = this.trailingRecordTags(record.text).map((tag) => `  - ${this.yamlQuote(tag)}`);
    const lines = [
      "---",
      `type: ${definition.typeName}`,
      `sentence: ${this.yamlQuote(sentence)}`,
      "owner:",
      ...owners.length ? owners : ["  - Unassigned"],
      `source: ${this.yamlQuote(`[[${sourceFile.basename}]]`)}`,
      `source_path: ${this.yamlQuote(sourceFile.path)}`,
      `date: ${date}`,
      `status: ${record.status ? this.normalizedStatus(record.status) : closed ? "Done" : "Open"}`,
      ...closed && record.doneDate ? [`completed_date: ${record.doneDate}`] : [],
      `record_id: ${record.id}`
    ];
    for (const field of Object.keys(this.settings.autoLinkTypes || {})) {
      const links = ((_a = record.typedLinks) == null ? void 0 : _a[field]) || [];
      if (!links.length) continue;
      lines.push(`${field}:`, ...links.map((l) => `  - ${this.yamlQuote(`[[${l.basename}]]`)}`));
    }
    if (this.settings.priorityEnabled) {
      const levels = this.settings.priorityLevels || ["None"];
      const priority = levels.includes(existingPriority) ? existingPriority : levels[0];
      lines.push(`priority: ${this.yamlQuote(priority)}`);
    }
    if (tags.length) lines.push("tags:", ...tags);
    lines.push("---", "", sentence, "", `Source: ${sourceLink}`, "");
    return lines.join("\n");
  }
  async syncRecordNotes(records, sourceFile, sourceLink, date) {
    var _a, _b, _c;
    const expected = /* @__PURE__ */ new Set();
    for (const record of records) {
      const folder = this.recordFolder(record.type);
      await this.ensureFolder(folder);
      const path = (0, import_obsidian2.normalizePath)(`${folder}/${this.recordFileName(record, date)}`);
      expected.add(path);
      const existing = this.app.vault.getAbstractFileByPath(path);
      const existingPriority = existing instanceof import_obsidian2.TFile ? (_b = (_a = this.app.metadataCache.getFileCache(existing)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.priority : void 0;
      const content = this.buildRecordNote(record, sourceFile, sourceLink, date, existingPriority);
      if (existing instanceof import_obsidian2.TFile) {
        const current = await this.app.vault.cachedRead(existing);
        if (current !== content) {
          await this.captureBefore(existing);
          this.processingPaths.add(existing.path);
          await this.app.vault.modify(existing, content);
          this.processingPaths.delete(existing.path);
        }
      } else {
        await this.app.vault.create(path, content);
        if (this.lastTransaction) this.lastTransaction.files.set(path, null);
      }
    }
    for (const definition of Object.values(RECORD_TYPES)) {
      const folder = (0, import_obsidian2.normalizePath)(this.settings[definition.folderSetting]);
      const prefix = folder + "/";
      for (const candidate of this.app.vault.getMarkdownFiles()) {
        if (!candidate.path.startsWith(prefix)) continue;
        const fm = (_c = this.app.metadataCache.getFileCache(candidate)) == null ? void 0 : _c.frontmatter;
        if ((fm == null ? void 0 : fm.source_path) !== sourceFile.path || !(fm == null ? void 0 : fm.record_id)) continue;
        if (expected.has(candidate.path)) continue;
        await this.captureBefore(candidate);
        await this.app.vault.delete(candidate);
      }
    }
  }
  buildKnowledgeBaseContent() {
    const priorityOn = Boolean(this.settings.priorityEnabled);
    const priorityOrder = priorityOn ? ["      - priority"] : [];
    const typeFilters = Object.values(RECORD_TYPES).map((d) => `    - 'type == "${d.typeName}"'`);
    const typeViews = Object.values(RECORD_TYPES).flatMap((d) => [
      "  - type: table",
      `    name: ${d.heading}`,
      "    filters:",
      "      and:",
      `        - 'type == "${d.typeName}"'`,
      "    order:",
      "      - sentence",
      "      - owner",
      ...priorityOrder,
      "      - source",
      "      - status",
      "      - date"
    ]);
    return [
      "filters:",
      "  or:",
      ...typeFilters,
      "properties:",
      "  type:",
      "    displayName: Type",
      "  sentence:",
      "    displayName: Sentence",
      "  owner:",
      "    displayName: Owner",
      ...priorityOn ? ["  priority:", "    displayName: Priority"] : [],
      "  source:",
      "    displayName: Source File",
      "  status:",
      "    displayName: Status",
      "  date:",
      "    displayName: Date",
      "views:",
      "  - type: table",
      "    name: All Open Items",
      "    filters:",
      "      and:",
      `        - 'status != "Done"'`,
      "    order:",
      "      - type",
      "      - sentence",
      "      - owner",
      ...priorityOrder,
      "      - source",
      "      - status",
      "      - date",
      ...typeViews,
      "  - type: table",
      "    name: By Owner",
      "    filters:",
      "      and:",
      `        - 'status != "Done"'`,
      "    groupBy:",
      "      property: owner",
      "      direction: ASC",
      "    order:",
      "      - type",
      "      - sentence",
      ...priorityOrder,
      "      - source",
      "      - status",
      "      - date",
      "  - type: table",
      "    name: Recently Done",
      "    filters:",
      "      and:",
      `        - 'status == "Done"'`,
      "    order:",
      "      - date",
      "      - type",
      "      - sentence",
      "      - owner",
      "      - source",
      ""
    ].join("\n");
  }
  async ensureKnowledgeBase() {
    const folder = (0, import_obsidian2.normalizePath)(this.settings.dashboardFolder || "01.Home/Dashboards");
    await this.ensureFolder(folder);
    const rawName = String(this.settings.dashboardBaseName || "00.\u{1F39B}\uFE0F Master").trim().replace(/\.base$/i, "");
    const baseName = this.safeFileName(rawName) || "00.\u{1F39B}\uFE0F Master";
    const path = (0, import_obsidian2.normalizePath)(`${folder}/${baseName}.base`);
    if (this.app.vault.getAbstractFileByPath(path)) return;
    await this.app.vault.create(path, this.buildKnowledgeBaseContent());
    if (this.lastTransaction) this.lastTransaction.files.set(path, null);
  }
  escapeRegExp(text) {
    return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  buildManagedBlock(records, personPath, type, sourcePath, sourceLink, date, start, end) {
    const relevant = records.filter((r) => r.type === type && r.people.some((p) => p.path === personPath));
    if (!relevant.length) return "";
    const lines = relevant.flatMap((r) => [
      `<!-- aceto-knowledge-os-record:${r.id}:${encodeURIComponent(sourcePath)}:${type} -->`,
      `- ${r.personDisplayText || r.displayText}`
    ]);
    return [start, `#### ${date} \xB7 ${sourceLink}`, ...lines, end].join("\n");
  }
  async syncRecordBlocksToPeople() {
    return 0;
  }
  removeLegacyManagedBlocks(content) {
    let updated = String(content || "");
    updated = updated.replace(
      /<!-- aceto-knowledge-os:[^\n:]+:(?:decisions|risks|issues|executive_follow_ups):start -->[\s\S]*?<!-- aceto-knowledge-os:[^\n:]+:(?:decisions|risks|issues|executive_follow_ups):end -->\n?/g,
      ""
    );
    updated = updated.replace(
      /<!-- aceto-metadata-sync:[^\n:]+:start -->[\s\S]*?<!-- aceto-metadata-sync:[^\n:]+:end -->\n?/g,
      ""
    );
    updated = updated.replace(
      /^#{1,6}\s+(Decisions|Risks|Issues|Executive Follow-ups)\s*\n(?=\s*(?:#{1,6}\s|$))/gim,
      ""
    );
    return updated.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
  }
  async removeLegacyPersonPageSections() {
    let changed = 0;
    const peopleFiles = this.app.vault.getMarkdownFiles().filter((file) => this.isPersonFile(file));
    for (const personFile of peopleFiles) {
      const original = await this.app.vault.cachedRead(personFile);
      const updated = this.removeLegacyManagedBlocks(original);
      if (updated === original) continue;
      await this.captureBefore(personFile);
      this.processingPaths.add(personFile.path);
      try {
        await this.app.vault.modify(personFile, updated);
      } finally {
        this.processingPaths.delete(personFile.path);
      }
      changed++;
    }
    return changed;
  }
  async syncKnowledgeOSStatusChanges() {
    const managedFolders = [this.settings.executiveFolder, this.settings.decisionsFolder, this.settings.risksFolder, this.settings.issuesFolder, this.settings.actionsFolder].map((folder) => (0, import_obsidian2.normalizePath)(folder || "")).filter(Boolean);
    const recordFiles = this.app.vault.getMarkdownFiles().filter((file) => {
      const path = (0, import_obsidian2.normalizePath)(file.path);
      return managedFolders.some((folder) => path.startsWith(folder + "/"));
    });
    if (!recordFiles.length) {
      new import_obsidian2.Notice("No Knowledge OS records were found.");
      return;
    }
    let changed = 0;
    let failed = 0;
    for (const recordFile of recordFiles) {
      try {
        if (await this.syncRecordStatusToSource(recordFile)) changed++;
      } catch (error) {
        console.error("ACE2X Knowledge OS status synchronization failed", recordFile.path, error);
        failed++;
      }
    }
    if (failed) {
      new import_obsidian2.Notice(`Knowledge OS status sync completed: ${changed} changed, ${failed} failed.`);
    } else if (changed) {
      new import_obsidian2.Notice(`Knowledge OS status sync completed: ${changed} source item${changed === 1 ? "" : "s"} updated.`);
    } else {
      new import_obsidian2.Notice("Knowledge OS status sync completed. No status changes were found.");
    }
  }
  readSimpleFrontmatter(content) {
    const match = String(content || "").match(/^---\s*\n([\s\S]*?)\n---(?:\s*\n|$)/);
    if (!match) return {};
    const result = {};
    for (const line of match[1].split("\n")) {
      const field = line.match(/^([A-Za-z0-9_-]+):\s*(.*?)\s*$/);
      if (!field) continue;
      let value = field[2].trim();
      if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
        value = value.slice(1, -1);
      }
      result[field[1]] = value;
    }
    return result;
  }
  async syncRecordStatusToSource(recordFile) {
    var _a;
    const recordContent = await this.app.vault.read(recordFile);
    const fm = this.readSimpleFrontmatter(recordContent);
    if (!(fm == null ? void 0 : fm.record_id) || !(fm == null ? void 0 : fm.source_path)) return false;
    const sourcePath = String(fm.source_path);
    const sourceFile = this.app.vault.getAbstractFileByPath(sourcePath);
    if (!(sourceFile instanceof import_obsidian2.TFile) || !this.shouldProcess(sourceFile)) return false;
    const indexed = this.index[sourcePath];
    const indexedRecord = (_a = indexed == null ? void 0 : indexed.records) == null ? void 0 : _a.find((record) => record.id === String(fm.record_id));
    if (!indexedRecord) return false;
    const desiredStatus = this.normalizedStatus(fm.status || "open");
    const original = await this.app.vault.cachedRead(sourceFile);
    let changed = false;
    const updated = original.split("\n").map((line) => {
      const match = line.match(new RegExp(`^(\\s*(?:[-*+]\\s*)?(${RECORD_TYPE_PATTERN})::\\s*)(.+?)(\\s*)$`, "i"));
      if (!match || match[2].toLowerCase() !== indexedRecord.type) return line;
      const parsedSourceStatus = this.parseInlineStatus(match[3]);
      if (this.canonicalRecordText(parsedSourceStatus.text) !== this.canonicalRecordText(indexedRecord.text)) return line;
      const nextBody = this.withInlineStatus(match[3], desiredStatus);
      const nextLine = `${match[1]}${nextBody}${match[4]}`;
      if (nextLine !== line) changed = true;
      return nextLine;
    }).join("\n");
    if (!changed) return false;
    this.processingPaths.add(sourcePath);
    try {
      await this.app.vault.modify(sourceFile, updated);
    } finally {
      this.processingPaths.delete(sourcePath);
    }
    const analysis = await this.analyzeFile(sourceFile);
    await this.applyAnalysis(analysis);
    await this.persist();
    return true;
  }
  async syncPersonStatusesToSources() {
    return false;
  }
};
var ACE2XKnowledgeOSSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ACE2X Knowledge OS" });
    new import_obsidian2.Setting(containerEl).setName("Automatic sync").setDesc("Process notes after saving. Manual preview is recommended.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
      this.plugin.settings.autoSync = value;
      await this.plugin.persist();
    }));
    const folderPaths = this.plugin.vaultFolderPaths();
    new import_obsidian2.Setting(containerEl).setName("Auto-detect folders").setDesc("Find likely People, Executive, Decisions, Risks, Issues and Dashboard folders when a configured location is missing.").addButton((button) => button.setButtonText("Detect folders").onClick(async () => {
      const changed = await this.plugin.autoDetectFolders();
      new import_obsidian2.Notice(changed ? "Folder locations updated." : "No better folder matches were found.");
      this.display();
    }));
    const validationResults = this.plugin.validateEnvironment();
    const validationIssues = validationResults.filter((result) => !result.ok).length;
    new import_obsidian2.Setting(containerEl).setName("Environment validation").setDesc(
      validationIssues ? `${validationIssues} configuration item${validationIssues === 1 ? "" : "s"} require attention. Validation reports issues but does not block ACE2X.` : "Required plugins and configured locations are ready."
    ).addButton((button) => button.setButtonText("Validate environment").setCta().onClick(() => this.plugin.showEnvironmentValidation()));
    this.addFolderPicker(containerEl, "People folder", "Folder containing person pages. Pages with type: person are also recognized elsewhere.", "peopleFolder", folderPaths);
    new import_obsidian2.Setting(containerEl).setName("Person template").setDesc("Template used when creating a missing person page.").addText((text) => text.setValue(this.plugin.settings.personTemplatePath).onChange(async (value) => {
      this.plugin.settings.personTemplatePath = (0, import_obsidian2.normalizePath)(value.trim());
      await this.plugin.persist();
    }));
    this.addFolderPicker(containerEl, "Executive follow-up folder", "Folder for e:: record notes.", "executiveFolder", folderPaths);
    this.addFolderPicker(containerEl, "Decisions folder", "Folder for decision record notes.", "decisionsFolder", folderPaths);
    this.addFolderPicker(containerEl, "Risks folder", "Folder for risk record notes.", "risksFolder", folderPaths);
    this.addFolderPicker(containerEl, "Issues folder", "Folder for issue record notes.", "issuesFolder", folderPaths);
    this.addFolderPicker(containerEl, "Actions folder", "Folder for a:: record notes.", "actionsFolder", folderPaths);
    this.addFolderPicker(containerEl, "Dashboard folder", "Folder where the master Base dashboard is created. Existing Base files are never overwritten.", "dashboardFolder", folderPaths);
    new import_obsidian2.Setting(containerEl).setName("Dashboard Base name").setDesc("Filename for the master Base. Enter a name without .base. Changing it creates the new Base on the next sync and does not delete the previous file.").addText((text) => text.setPlaceholder("00.\u{1F39B}\uFE0F Master").setValue(this.plugin.settings.dashboardBaseName || "00.\u{1F39B}\uFE0F Master").onChange(async (value) => {
      this.plugin.settings.dashboardBaseName = value.trim().replace(/\.base$/i, "") || "00.\u{1F39B}\uFE0F Master";
      await this.plugin.persist();
    }));
    new import_obsidian2.Setting(containerEl).setName("Create unresolved links as people").setDesc("Off by default. When enabled, unresolved links inside d::, r::, i:: or e:: records create person pages.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoCreatePeople).onChange(async (value) => {
      this.plugin.settings.autoCreatePeople = value;
      await this.plugin.persist();
    }));
    new import_obsidian2.Setting(containerEl).setName("Excluded folders").setDesc("Comma-separated vault paths.").addTextArea((text) => text.setValue((this.plugin.settings.excludedFolders || []).join(", ")).onChange(async (value) => {
      this.plugin.settings.excludedFolders = value.split(",").map((x) => (0, import_obsidian2.normalizePath)(x.trim())).filter(Boolean);
      await this.plugin.persist();
    }));
    new import_obsidian2.Setting(containerEl).setName("Excluded headings").setDesc("Comma-separated heading prefixes ignored during analysis.").addTextArea((text) => text.setValue((this.plugin.settings.excludedHeadings || []).join(", ")).onChange(async (value) => {
      this.plugin.settings.excludedHeadings = value.split(",").map((x) => x.trim().toLowerCase()).filter(Boolean);
      await this.plugin.persist();
    }));
    new import_obsidian2.Setting(containerEl).setName("Enable priority field").setDesc("Adds an editable Priority property to record notes and the dashboard Base.").addToggle((toggle) => toggle.setValue(this.plugin.settings.priorityEnabled).onChange(async (value) => {
      this.plugin.settings.priorityEnabled = value;
      await this.plugin.persist();
      this.display();
    }));
    if (this.plugin.settings.priorityEnabled) {
      new import_obsidian2.Setting(containerEl).setName("Priority levels").setDesc("Comma-separated, in order. The first level is the default for new records.").addText((text) => text.setValue((this.plugin.settings.priorityLevels || []).join(", ")).onChange(async (value) => {
        this.plugin.settings.priorityLevels = value.split(",").map((x) => x.trim()).filter(Boolean);
        await this.plugin.persist();
      }));
    }
    containerEl.createEl("h3", { text: "Meeting Mode" });
    const personPaths = this.plugin.personFilePaths();
    new import_obsidian2.Setting(containerEl).setName("Your person note").setDesc("Excludes you from Smart Owner Detection's candidate list when Meeting Mode reads a note's participants/people/owner.").addDropdown((dropdown) => {
      dropdown.addOption("", "None selected");
      for (const path of personPaths) dropdown.addOption(path, path);
      dropdown.setValue(this.plugin.settings.yourPersonNote || "");
      dropdown.onChange(async (value) => {
        this.plugin.settings.yourPersonNote = value;
        await this.plugin.persist();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Open panel automatically for meeting notes").setDesc("Opens the Meeting Mode panel when a note with a participants or owner frontmatter field becomes active.").addToggle((toggle) => toggle.setValue(this.plugin.settings.meetingModeAutoOpen).onChange(async (value) => {
      this.plugin.settings.meetingModeAutoOpen = value;
      await this.plugin.persist();
    }));
    new import_obsidian2.Setting(containerEl).setName("Remember last owner").setDesc("Pre-select the previously used owner across captures when it's among the current note's candidates.").addToggle((toggle) => toggle.setValue(this.plugin.settings.meetingModeRememberOwner).onChange(async (value) => {
      this.plugin.settings.meetingModeRememberOwner = value;
      await this.plugin.persist();
    }));
    new import_obsidian2.Setting(containerEl).setName("Remember last category").setDesc("Pre-fill the Quick Capture prefix (d:: r:: i:: e:: a::) from your last capture.").addToggle((toggle) => toggle.setValue(this.plugin.settings.meetingModeRememberCategory).onChange(async (value) => {
      this.plugin.settings.meetingModeRememberCategory = value;
      await this.plugin.persist();
    }));
    new import_obsidian2.Setting(containerEl).setName("Show live counters").setDesc("Display per-type record counts in the Meeting Mode panel.").addToggle((toggle) => toggle.setValue(this.plugin.settings.meetingModeShowCounters).onChange(async (value) => {
      this.plugin.settings.meetingModeShowCounters = value;
      await this.plugin.persist();
    }));
    new import_obsidian2.Setting(containerEl).setName("Focus after save").setDesc("Refocus the Quick Capture field after each capture, keeping your hands on the keyboard.").addToggle((toggle) => toggle.setValue(this.plugin.settings.meetingModeFocusAfterSave).onChange(async (value) => {
      this.plugin.settings.meetingModeFocusAfterSave = value;
      await this.plugin.persist();
    }));
    this.renderTermsReference(containerEl);
  }
  addFolderPicker(containerEl, name, description, settingKey, folderPaths) {
    const current = (0, import_obsidian2.normalizePath)(this.plugin.settings[settingKey] || "");
    const exists = current && this.app.vault.getAbstractFileByPath(current) instanceof import_obsidian2.TFolder;
    const setting = new import_obsidian2.Setting(containerEl).setName(name).setDesc(exists ? description : `${description} Current location is missing; select a folder or run auto-detect.`);
    setting.addDropdown((dropdown) => {
      if (current && !folderPaths.includes(current)) dropdown.addOption(current, `\u26A0 ${current} (missing)`);
      for (const path of folderPaths) dropdown.addOption(path, path);
      dropdown.setValue(current || folderPaths[0] || "");
      dropdown.onChange(async (value) => {
        this.plugin.settings[settingKey] = (0, import_obsidian2.normalizePath)(value);
        await this.plugin.persist();
        this.display();
      });
    });
    return setting;
  }
  renderTermsReference(containerEl) {
    containerEl.createEl("h3", { text: "Syntax reference" });
    const reference = containerEl.createDiv({ cls: "aceto-terms-reference" });
    const table = reference.createEl("table");
    const head = table.createEl("thead").createEl("tr");
    head.createEl("th", { text: "Syntax" });
    head.createEl("th", { text: "Meaning" });
    head.createEl("th", { text: "Example" });
    const body = table.createEl("tbody");
    const rows = [
      ["d::", "Decision", "d:: [[John Doe|JD]] approved the proposal.", "d"],
      ["r::", "Risk", "r:: Vendor delays may impact the schedule. [[John Doe]]", "r"],
      ["i::", "Issue", "i:: Reporting currently requires administrator access.", "i"],
      ["e::", "Executive follow-up", "e:: Confirm FY27 funding with [[John Doe]].", "e"],
      ["a::", "Action (delegated to someone else)", "a:: Confirm pricing with the vendor. [[John Doe]]", "a"],
      ["[[Name]]", "Person reference", "[[John Doe]] or an alias such as [[JD]]"],
      ["- [ ]", "Your task", "- [ ] Review licensing \u{1F4C5} 2026-07-31"],
      ["#Topic", "Tag", "#Infrastructure or #IAM"],
      ["s::o / s::d", "Inline status", "d:: [[John Doe]] Approve the proposal. #Infrastructure s::o"],
      ["done::", "Completion date", "~~d:: [[John Doe]] Approve the proposal. s::d done::2026-07-18~~"],
      ["~~text~~", "Completed-record formatting", "~~d:: Decision approved. s::d done::2026-07-18~~"]
    ];
    for (const row of rows) {
      const tr = body.createEl("tr");
      const codeEl = tr.createEl("td").createEl("code", { text: row[0] });
      if (row[3]) codeEl.addClass(`aceto-type-marker-${row[3]}`);
      tr.createEl("td", { text: row[1] });
      tr.createEl("td").createEl("code", { text: row[2] });
    }
    const notes = reference.createEl("div", { cls: "aceto-reference-notes" });
    notes.createEl("p", { text: "The d:: r:: i:: e:: a:: markers above are shown with the same colors used to highlight them inline in your notes, in both edit mode and reading view." });
    notes.createEl("p", { text: "Aliases are resolved by Obsidian. A link such as [[JD]] resolves to the person page whose aliases include JD." });
    notes.createEl("p", { text: "Only links resolving to a person page are synchronized to People pages. A person page is recognized by its location in the People folder or by type: person in frontmatter." });
    notes.createEl("p", { text: "Use s:: inline at the end of a record. Write s::o for Open and s::d for Done. The aliases s::c, done, closed, and complete are accepted and normalized. Base status edits synchronize back to the compact inline value." });
    notes.createEl("p", { text: "When a record becomes Done, synchronization applies strikethrough and adds done:: YYYY-MM-DD. Reopening removes both the strikethrough and completion date." });
    notes.createEl("p", { text: "Editing, changing status, removing a person, or deleting a record updates every associated person page the next time the source note is synced." });
  }
};
